# Generated by Django 3.1.1 on 2020-12-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201224_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='enos',
            new_name='eno',
        ),
    ]
