# Generated by Django 3.1.1 on 2020-12-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201225_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jno', models.IntegerField()),
                ('jname', models.CharField(max_length=64)),
                ('jsal', models.FloatField()),
                ('jaddress', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
