# Generated by Django 3.1.1 on 2020-12-28 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201228_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='jaddress',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='jname',
        ),
        migrations.AddField(
            model_name='jobs',
            name='jcompanyname',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='jexperience',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='jlocation',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='jnotificationdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='jtitle',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jsal',
            field=models.FloatField(null=True),
        ),
    ]
