# Generated by Django 3.1.1 on 2020-12-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_jobs_japply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japply', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='japply',
        ),
    ]
