# Generated by Django 3.1.1 on 2020-12-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201228_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs_apply',
        ),
    ]
